[package]
name = "client"
version.workspace = true
edition.workspace = true

[dependencies]
protocol = { path = "../protocol" }
tokio-tungstenite.workspace = true
tokio = { workspace = true, features = ["full"] }
futures.workspace = true
anyhow.workspace = true
uuid.workspace = true
thiserror.workspace = true
slint.workspace = true
reqwest = { workspace = true, features = ["json"] }
async-compat.workspace = true
email_address.workspace = true

[build-dependencies]
slint-build.workspace = true
