[workspace]
resolver = "3"
members = ["client", "protocol", "server"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
tokio = "1.37.0"
tokio-util = "0.7.15"
futures = "0.3.31"
anyhow = "1.0.98"
tonic = "0.14.0"
tonic-prost = "0.14.0"
tonic-prost-build = "0.14.0"
prost = "0.14.1"
