[workspace]
resolver = "3"
members = ["client", "protocol", "server"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
serde = "1.0.219"
bitcode = "0.6.6"
bytes = "1.10.1"
tokio = "1.47.1"
thiserror = "2.0.14"
tokio-util = "0.7.15"
futures = "0.3.31"
anyhow = "1.0.98"

# TONIC SLOP QUARANTINE holy shit
tonic = "0.14.0"
tonic-prost = "0.14.0"
tonic-prost-build = "0.14.0"
prost = "0.14.1"
#######################

tower = "0.5.2"
http = "1.3.1"
semver = "1.0.26"
sqlx = "0.8.6"
uuid = "1.17.0"
