import { Palette } from "../../palette.slint";
import { LineEdit, TextEdit } from "../../widgets.slint";

export component ChatInput inherits Rectangle {
    in-out property <string> text <=> edit.text;

    callback on_send(message: string);

    background: Palette.background2;

    HorizontalLayout {
        spacing: 5px;

        edit := TextEdit {
            init => { self.has-focus = true; }
            placeholder: "Message";
            min-height: 32px;
            max-height: 90px;
            accepted(text) => {
                on_send(text);
                self.text = "";
            }
        }
        
        VerticalLayout {
            alignment: start;

            Image {
                source: @image-url("../../images/save.svg");
                width: 32px;
                height: 32px;
                colorize: send_toucharea.pressed ? Palette.text1 : Palette.accent;

                animate colorize {
                    duration: 100ms;
                }

                send_toucharea := TouchArea {
                    mouse-cursor: pointer;
                    clicked => {
                        on_send(edit.text);
                        edit.text = "";
                    }
                }
            }
        }
    }
}