import { Palette } from "../../palette.slint";
import { PanelView, ErrorText } from "panel-view.slint";
import { Button, Text, LineEdit } from "../../widgets.slint";

export component Register1Panel inherits PanelView {
	in property <bool> enabled: true;
	in property <string> error_message <=> error.text;
	in property <bool> email_error <=> email.error;

	out property <string> email <=> email.text;
	callback action <=> button.clicked;

    Text {
        text: "New account";
        horizontal-alignment: left;
    }
    email := LineEdit {
        placeholder-text: "email";
        enabled: root.enabled;
        accepted(text) => { button.clicked() }
    }
    button := Button {
        text: "verify";
        enabled: root.enabled;
    }
    error := ErrorText {}
}