import { Palette } from "palette.slint";
import { Button, Text, LineEdit, LoadingAnimation } from "widgets.slint";

export enum PanelView {
    login,
    register
}

export component EntryWindow inherits Window {
    in property <string> build-info: "v0.0";
    
    out property <string> login_username <=> login_username.text;
    out property <string> login_password <=> login_password.text;
    out property <string> register_username <=> register_username.text;
    out property <string> register_password <=> register_password.text;
    out property <string> register_password2 <=> register_password2.text;

    in-out property <bool> login_username_error <=> login_username.error;
    in-out property <bool> login_password_error <=> login_password.error;
    in-out property <bool> register_username_error <=> register_username.error;
    in-out property <bool> register_password_error <=> register_password.error;
    in-out property <bool> register_password2_error <=> register_password2.error;

    in-out property <string> login_error <=> login_error.text;
    in-out property <string> register_error <=> register_error.text;

    property <PanelView> panel_view;

    title: "Salix";
    width: 400px;
    background: Palette.background1;

    callback login(username: string, password: string);
    callback register(username: string, password: string);

    public function set_loading(b: bool) {
        login_username.enabled = !b;
        login_password.enabled = !b;
        login_button.enabled = !b;

        register_username.enabled = !b;
        register_password.enabled = !b;
        register_password2.enabled = !b;
        register_button.enabled = !b;

        loading.running = b;
        loading.opacity = b ? 1 : 0;
    }

    function unmark_errors() {
        login_username.error = false;
        login_password.error = false;
        register_username.error = false;
        register_password.error = false;
        register_password2.error = false;

        login_error.text = "";
        register_error.text = "";
    }

    function login_click() {
        unmark_errors();

        if login_username.text == "" {
            login_username.error = true;
            login_error.text = "enter the username";
            return;
        }
        if login_password.text == "" {
            login_password.error = true;
            login_error.text = "enter the password";
            return;
        }

        set_loading(true);

        login(login_username.text, login_password.text);
    }

    function register_click() {
        unmark_errors();
        
        if register_username.text == "" {
            register_username.error = true;
            register_error.text = "enter the username";
            return;
        }
        if register_password.text == "" {
            register_password.error = true;
            register_error.text = "enter the password";
            return;
        }
        if register_password.text != register_password2.text {
            register_password2.error = true;
            register_error.text = "password must match";
            return;
        }

        set_loading(true);

        register(register_username.text, register_password.text)
    }

    VerticalLayout {
        Text {
            text: "salix";
            font-size: 50px;
            font-weight: 800;
            color: Palette.accent;
            horizontal-alignment: center;
            vertical-stretch: 0;
        }

        HorizontalLayout {
            x: panel_view == PanelView.login ? 0px : -root.width;
            width: 2 * root.width;

            animate x {
                duration: 1s;
                easing: ease-out-expo;
            }

            VerticalLayout {
                width: 50%;
                padding: 15px;
                alignment: start;
                spacing: 7px;

                login_panel := Rectangle {
                    background: Palette.background2;
                    vertical-stretch: 1;

                    VerticalLayout {
                        padding: 7px;
                        padding-left: 20px;
                        padding-right: 20px;
                        spacing: 10px;

                        Text {
                            text: "Login";
                            horizontal-alignment: left;
                        }
                        login_username := LineEdit {
                            placeholder-text: "username";
                            init => { self.focus() }
                            accepted(text) => { login_button.clicked() }
                        }
                        login_password := LineEdit {
                            placeholder-text: "password";
                            input-type: password;
                            accepted(text) => { login_button.clicked() }
                        }
                        login_button := Button {
                            text: "login";

                            clicked => {
                                login_click();
                            }
                        }
                        login_error := Text {
                            color: Palette.error;
                            horizontal-alignment: center;
                            wrap: word-wrap;
                        }
                    }
                }
                HorizontalLayout {
                    alignment: end;
                    Text {
                        text: "or register";
                        font-weight: 700;
                        color: Palette.accent;

                        TouchArea {
                            mouse-cursor: pointer;
                            clicked => {
                                panel_view = PanelView.register;
                            }
                        }
                    }
                }
            }

            VerticalLayout {
                width: 50%;
                padding: 15px;
                alignment: start;
                spacing: 7px;

                register_panel := Rectangle {
                    background: Palette.background2;
                    vertical-stretch: 1;

                    VerticalLayout {
                        padding: 7px;
                        padding-left: 20px;
                        padding-right: 20px;
                        spacing: 10px;

                        Text {
                            text: "New account";
                            horizontal-alignment: left;
                        }
                        register_username := LineEdit {
                            placeholder-text: "username";
                            accepted(text) => { register_button.clicked() }
                        }
                        register_password := LineEdit {
                            placeholder-text: "password";
                            input-type: password;
                            accepted(text) => { register_button.clicked() }
                        }
                        register_password2 := LineEdit {
                            placeholder-text: "password";
                            input-type: password;
                            accepted(text) => { register_button.clicked() }
                        }
                        register_button := Button {
                            text: "create";

                            clicked => {
                                register_click();
                            }
                        }
                        register_error := Text {
                            color: Palette.error;
                            horizontal-alignment: center;
                            wrap: word-wrap;
                        }
                    }
                }
                HorizontalLayout {
                    alignment: start;
                    Text {
                        text: "or login";
                        font-weight: 700;
                        color: Palette.accent;
                        horizontal-alignment: left;

                        TouchArea {
                            mouse-cursor: pointer;
                            clicked => {
                                panel_view = PanelView.login;
                            }
                        }
                    }
                }
            }
        }

        loading := LoadingAnimation {
            size: 128px;
            running: false;
            opacity: 0;
            x: (root.width - self.size) / 2;

            animate opacity {
                duration: 1s;
                easing: ease;
            }
        }

        HorizontalLayout {
            padding-right: 15px;
            padding-bottom: 10px;
            alignment: end;

            Text {
                text: root.build-info;
                color: Palette.text2;
                horizontal-alignment: right;
            }
        }
    }
}