[package]
name = "protocol"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror.workspace = true
bitcode = { workspace = true, features = ["derive"] }
semver.workspace = true
tokio = { workspace = true, features = ["io-util"] }
