import { Palette } from "../palette.slint";
import { Button, Text, LineEdit, LoadingAnimation, TextEdit, Footer } from "../widgets.slint";
import { ListView } from "std-widgets.slint";
import { MessageData, Message } from "chat/chat-message.slint";
import { ChatInput } from "chat/chat-input.slint";

export component ChatWindow inherits Window {
	in property <[MessageData]> messages: [
		{author: "Sample", text: "example text message"},
		{author: "Another User", text: "LOL"},
	];

	callback on_send <=> input.on_send;

	title: "Salix";
    background: Palette.background1;
    min-height: 600px;
    min-width: 800px;
    
    VerticalLayout {
    	alignment: start;
    	Footer {}
    }

    VerticalLayout {
    	Rectangle {
    		ListView {
    			width: 100%;
    			height: 100%;
    			horizontal-scrollbar-policy: always-off;

    			for msg in root.messages : Message {
	                data: msg;
	            }
    		}
    	}
    	input := ChatInput {}
    }
}