import { Palette } from "../palette.slint";
import { LoadingAnimation, Footer } from "../widgets.slint";

export component LoadingWindow inherits Window {
    title: "Salix";
    background: Palette.background1;

    VerticalLayout {
    	VerticalLayout {
	    	padding: 15px;

	    	LoadingAnimation {
	            size: 256px;
	            running: true;
	        }
	    }

        Footer {}
    }
}
