[package]
name = "server"
version.workspace = true
edition.workspace = true

[dependencies]
protocol = { path = "../protocol" }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["compat"] }
futures.workspace = true
anyhow.workspace = true
tower.workspace = true
http.workspace = true
semver.workspace = true
sqlx = { workspace = true, features = ["runtime-tokio", "postgres", "uuid"] }
uuid.workspace = true
