# The default configuration file for the Salix server

# Socket to which bind the server
bind_to = "0.0.0.0:3000"
# Postgres database url
database_url = "postgres://localhost/salix"

[email]
noreply = "smtps://user:pass@hostname:port"
