import { Palette } from "../palette.slint";
import { GlobalData } from "../global_data.slint";
import { Text } from "text.slint";

export component Footer {
    HorizontalLayout {
        padding-right: 15px;
        padding-left: 15px;
        padding-bottom: 10px;
        padding-top: 10px;
        spacing: 5px;
        alignment: end;

        vertical-stretch: 0;

        TouchArea {
        	Text {
        		text: "license";
        		color: Palette.accent;
                font-size: 10px;
        	}
        	mouse-cursor: pointer;

        	clicked => {
        		GlobalData.show-license();
        	}
        }

        Text {
            text: GlobalData.build-info;
            color: Palette.text2;
            font-size: 10px;
        }
    }
}